CAP_MAX_POP = true
CONTRACTIONS_TYPE = "gerry"
CONTRACTIONS_PER_STEP = 500
INPUT_GRAPH_FILE = "TX_vtds_clean.json"
EXPERIMENT_NAME = "TX_gerry_contract_capped_pop"
BASE_CHAIN_NUM_STEPS = 35000
CHAIN_NUM_STEPS = 60000
NUM_PROCESSES = 7
EPSILON = 0.05
ELECTION_STATISTIC = "seats"
NUM_PARTS = 38
DISTANCE_TO_METAMANDER = 3
DUAL_SCORE_DIVISOR = 3
POP_COL = "TOTPOP"
ASSIGN_COL = "USCD"
ELECTION_NAME = "2016_Presidential"
PARTY_A_COL = "PRES16R"
PARTY_B_COL = "PRES16D"
X_POSITION = "C_X"
Y_POSITION = "C_Y"
SCORE_FUNC = "score_by_party"
